INSERT INTO cinema.hall (id, name_hall)
VALUES (DEFAULT, 'RED HALL') ON CONFLICT DO NOTHING;
INSERT INTO cinema.hall (id, name_hall)
VALUES (DEFAULT, 'GREEN HALL') ON CONFLICT DO NOTHING;
INSERT INTO cinema.hall (id, name_hall)
VALUES (DEFAULT, '3D HALL') ON CONFLICT DO NOTHING;